# FreshMart - FMCG Forecasting & Inventory Management

# Step 1: Load Dataset

In [8]:

import pandas as pd

# Load dataset
df = pd.read_csv("../data/raw/supermarket_sales.csv")

# Show first 5 rows
df.head()

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,350.114418,297.998070,52.116348,0.148855,154,31,11,20.0,M,1
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,106.034197,80.626759,25.407438,0.239616,130,24,5,26.0,F,1
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,1044.900114,906.165848,138.734266,0.132773,270,44,8,27.0,F,0
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811402,...,521.759920,391.622805,130.137115,0.249420,403,63,8,NaN,F,0
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,91.873416,70.715665,21.157751,0.230292,366,40,9,60.0,F,1

In [9]:
# Check dataset size
print(df.shape)

(100000, 21)

In [10]:
# Show column names
print(df.columns)

Index(['Invoice_ID', 'Invoice_Date', 'City', 'Store_Format', 'Category',
       'Brand', 'Channel', 'Payment_Mode', 'Units', 'Cost_Price',
       'Selling_Price', 'Revenue', 'Cost', 'Margin', 'Margin_%',
       'Stock_On_Hand', 'Reorder_Level', 'Lead_Time_Days', 'Customer_Age',
       'Customer_Gender', 'Loyalty_Flag'],
      dtype='str')

In [11]:
# Basic information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Invoice_ID       100000 non-null  int64
 1   Invoice_Date     100000 non-null  str
 2   City             100000 non-null  str
 3   Store_Format     100000 non-null  str
 4   Category         100000 non-null  str
 5   Brand            100000 non-null  str
 6   Channel          100000 non-null  str
 7   Payment_Mode     100000 non-null  str
 8   Units            100000 non-null  int64
 9   Cost_Price       100000 non-null  float64
 10  Selling_Price    100000 non-null  float64
 11  Revenue          100000 non-null  float64
 12  Cost             100000 non-null  float64
 13  Margin           100000 non-null  float64
 14  Margin_%         100000 non-null  float64
 15  Stock_On_Hand    100000 non-null  int64
 16  Reorder_Level    100000 non-null  int64
 17  Lead_Time_Days   100000 non-null  int64
 18  Customer_Age     59919 non-null   float64
 19  Customer_Gender  94952 non-null   str
 20  Loyalty_Flag     100000 non-null  int64
dtypes: float64(7), int64(6), str(8)
memory usage: 16.0 MB

In [12]:
# Create copy of original dataset
clean_df = df.copy()

print("Copy created successfully")

Copy created successfully

In [14]:
# Convert date column
clean_df["Invoice_Date"] = pd.to_datetime(
    clean_df["Invoice_Date"]
)

# Check datatype
print(clean_df["Invoice_Date"].dtype)
df.head()

datetime64[us]

,Invoice_ID,Invoice_Date,City,Store_Format,Category,Brand,Channel,Payment_Mode,Units,Cost_Price,...,Revenue,Cost,Margin,Margin_%,Stock_On_Hand,Reorder_Level,Lead_Time_Days,Customer_Age,Customer_Gender,Loyalty_Flag
0,58018430,2024-02-02 13:50:00,Kolkata,Super,Grocery,Nestle,Online,Wallet,2,148.999035,...,350.114418,297.998070,52.116348,0.148855,154,31,11,20.0,M,1
1,48157952,2024-10-09 11:52:00,Hyderabad,Hyper,Home Care,PepsiCo,Offline,Wallet,1,80.626759,...,106.034197,80.626759,25.407438,0.239616,130,24,5,26.0,F,1
2,23283831,2024-08-26 22:03:00,Chennai,Hyper,Snacks,PepsiCo,Online,Card,5,181.233170,...,1044.900114,906.165848,138.734266,0.132773,270,44,8,27.0,F,0
3,53537460,2024-06-09 04:34:00,Bengaluru,Hyper,Beverages,Nestle,Omnichannel,Card,2,195.811402,...,521.759920,391.622805,130.137115,0.249420,403,63,8,NaN,F,0
4,55348596,2024-06-07 01:13:00,Delhi,Super,Snacks,ITC,Offline,Card,3,23.571888,...,91.873416,70.715665,21.157751,0.230292,366,40,9,60.0,F,1

In [15]:
# Check missing values
clean_df.isnull().sum()

Invoice_ID             0
Invoice_Date           0
City                   0
Store_Format           0
Category               0
Brand                  0
Channel                0
Payment_Mode           0
Units                  0
Cost_Price             0
Selling_Price          0
Revenue                0
Cost                   0
Margin                 0
Margin_%               0
Stock_On_Hand          0
Reorder_Level          0
Lead_Time_Days         0
Customer_Age       40081
Customer_Gender     5048
Loyalty_Flag           0
dtype: int64

In [16]:
# Fill missing age with median
clean_df["Customer_Age"] = clean_df[
    "Customer_Age"
].fillna(
    clean_df["Customer_Age"].median()
)

print("Age missing values fixed")

Age missing values fixed

In [17]:
# Fill gender with mode
clean_df["Customer_Gender"] = clean_df[
    "Customer_Gender"
].fillna(
    clean_df["Customer_Gender"].mode()[0]
)

print("Gender missing values fixed")

Gender missing values fixed

In [18]:
clean_df.isnull().sum()

Invoice_ID         0
Invoice_Date       0
City               0
Store_Format       0
Category           0
Brand              0
Channel            0
Payment_Mode       0
Units              0
Cost_Price         0
Selling_Price      0
Revenue            0
Cost               0
Margin             0
Margin_%           0
Stock_On_Hand      0
Reorder_Level      0
Lead_Time_Days     0
Customer_Age       0
Customer_Gender    0
Loyalty_Flag       0
dtype: int64

In [19]:
# Check minimum values
clean_df[
    [
        "Units",
        "Cost_Price",
        "Selling_Price",
        "Revenue",
        "Cost",
        "Stock_On_Hand",
        "Lead_Time_Days"
    ]
].min()

Units              1.000000
Cost_Price        10.000526
Selling_Price     10.580915
Revenue           10.653198
Cost              10.002024
Stock_On_Hand     50.000000
Lead_Time_Days     3.000000
dtype: float64

In [20]:
# Check maximum values
clean_df[
    [
        "Units",
        "Cost_Price",
        "Selling_Price",
        "Revenue",
        "Stock_On_Hand",
        "Lead_Time_Days",
        "Customer_Age"
    ]
].max()

Units                5.000000
Cost_Price         199.999659
Selling_Price      289.699598
Revenue           1443.134985
Stock_On_Hand      499.000000
Lead_Time_Days      14.000000
Customer_Age        64.000000
dtype: float64

In [21]:
wrong_price = clean_df[
    clean_df["Selling_Price"]
    < clean_df["Cost_Price"]
]

print(wrong_price.shape)

(0, 21)

In [22]:
print(clean_df.duplicated().sum())

0

In [23]:
print(clean_df["Category"].unique())
print(clean_df["Brand"].unique())

<StringArray>
[      'Grocery',     'Home Care',        'Snacks',     'Beverages',
         'Dairy', 'Personal Care',    'Vegetables',        'Fruits']
Length: 8, dtype: str
<StringArray>
['Nestle', 'PepsiCo', 'ITC', 'Tata', 'Britannia', 'Amul', 'Parle', 'HUL']
Length: 8, dtype: str

In [24]:
clean_df.duplicated().sum()

np.int64(0)

In [25]:
clean_df["Category"].unique()

<StringArray>
[      'Grocery',     'Home Care',        'Snacks',     'Beverages',
         'Dairy', 'Personal Care',    'Vegetables',        'Fruits']
Length: 8, dtype: str

In [ ]:
clean_df["Category"].unique()

<StringArray>
[      'Grocery',     'Home Care',        'Snacks',     'Beverages',
         'Dairy', 'Personal Care',    'Vegetables',        'Fruits']
Length: 8, dtype: str

In [26]:
valid_brand_category = {
    "Grocery": ["Tata", "ITC"],
    
    "Home Care": ["HUL", "Tata"],
    
    "Snacks": ["PepsiCo", "Parle", "ITC", "Britannia"],
    
    "Beverages": ["PepsiCo", "Nestle", "Tata"],
    
    "Dairy": ["Amul", "Nestle"],
    
    "Personal Care": ["HUL"],
    
    "Vegetables": ["Tata"],
    
    "Fruits": ["Tata"]
}

In [27]:
clean_df = clean_df[
    clean_df.apply(
        lambda row:
        row["Brand"] in valid_brand_category[
            row["Category"]
        ],
        axis=1
    )
]

print(clean_df.shape)

(25032, 21)

In [28]:
clean_df.groupby(
    "Category"
)["Brand"].unique()

Category
Beverages                 [Nestle, PepsiCo, Tata]
Dairy                              [Nestle, Amul]
Fruits                                     [Tata]
Grocery                               [Tata, ITC]
Home Care                             [Tata, HUL]
Personal Care                               [HUL]
Snacks           [PepsiCo, ITC, Britannia, Parle]
Vegetables                                 [Tata]
Name: Brand, dtype: object

In [30]:
clean_df.groupby(
    "Category"
)["Brand"].unique()
clean_df.groupby("Category")["Brand"].unique()

Category
Beverages                 [Nestle, PepsiCo, Tata]
Dairy                              [Nestle, Amul]
Fruits                                     [Tata]
Grocery                               [Tata, ITC]
Home Care                             [Tata, HUL]
Personal Care                               [HUL]
Snacks           [PepsiCo, ITC, Britannia, Parle]
Vegetables                                 [Tata]
Name: Brand, dtype: object

In [31]:
import random

product_mapping = {

    ("Dairy", "Amul"): [
        "Amul Milk",
        "Amul Butter",
        "Amul Cheese",
        "Amul Curd"
    ],

    ("Dairy", "Nestle"): [
        "Nestle Yogurt",
        "Nestle Milk Powder",
        "Nestle Greek Yogurt"
    ],

    ("Snacks", "PepsiCo"): [
        "Lays Classic",
        "Lays Magic Masala",
        "Kurkure Masala",
        "Doritos Nacho"
    ],

    ("Snacks", "Parle"): [
        "Parle-G Biscuits",
        "Monaco Biscuits",
        "Hide & Seek"
    ],

    ("Snacks", "Britannia"): [
        "Good Day Biscuit",
        "Marie Gold",
        "50-50 Biscuit"
    ],

    ("Snacks", "ITC"): [
        "Bingo Chips",
        "Sunfeast Biscuits",
        "Yippee Noodles"
    ],

    ("Beverages", "PepsiCo"): [
        "Pepsi 750ml",
        "Mountain Dew",
        "7UP Bottle"
    ],

    ("Beverages", "Nestle"): [
        "Nescafe Coffee",
        "Milo Drink"
    ],

    ("Beverages", "Tata"): [
        "Tata Tea",
        "Tata Coffee"
    ],

    ("Grocery", "Tata"): [
        "Tata Salt",
        "Tata Sampann Dal",
        "Tata Rice"
    ],

    ("Grocery", "ITC"): [
        "Aashirvaad Atta",
        "Sunfeast Pasta"
    ],

    ("Home Care", "HUL"): [
        "Surf Excel",
        "Vim Liquid",
        "Comfort Fabric"
    ],

    ("Home Care", "Tata"): [
        "Tata Cleaning Powder"
    ],

    ("Personal Care", "HUL"): [
        "Dove Soap",
        "Lux Soap",
        "Clinic Plus Shampoo"
    ],

    ("Fruits", "Tata"): [
        "Apple Pack",
        "Banana Pack",
        "Orange Pack"
    ],

    ("Vegetables", "Tata"): [
        "Tomato Pack",
        "Potato Pack",
        "Onion Pack"
    ]
}

In [32]:
# Generate product name

clean_df["Product_Name"] = clean_df.apply(
    lambda row: random.choice(
        product_mapping[
            (row["Category"], row["Brand"])
        ]
    ),
    axis=1
)

print("Product column created!")

Product column created!

In [33]:
clean_df[
    [
        "Category",
        "Brand",
        "Product_Name"
    ]
].head(20)

         Category      Brand          Product_Name
2          Snacks    PepsiCo     Lays Magic Masala
3       Beverages     Nestle        Nescafe Coffee
4          Snacks        ITC     Sunfeast Biscuits
5         Grocery       Tata             Tata Salt
7       Beverages    PepsiCo            7UP Bottle
14         Snacks    PepsiCo        Kurkure Masala
18         Snacks        ITC           Bingo Chips
19         Fruits       Tata           Orange Pack
21         Fruits       Tata           Orange Pack
25      Home Care       Tata  Tata Cleaning Powder
31  Personal Care        HUL              Lux Soap
34      Beverages    PepsiCo            7UP Bottle
35      Beverages     Nestle        Nescafe Coffee
36      Beverages     Nestle            Milo Drink
37         Snacks  Britannia      Good Day Biscuit
39  Personal Care        HUL             Dove Soap
44         Snacks        ITC     Sunfeast Biscuits
46        Grocery       Tata             Tata Salt
51      Home Care        HUL            Vim Liquid
56      Home Care       Tata  Tata Cleaning Powder

In [34]:
clean_df["Revenue"] = (
    clean_df["Units"]
    * clean_df["Selling_Price"]
)

In [35]:
clean_df["Cost"] = (
    clean_df["Units"]
    * clean_df["Cost_Price"]
)

In [38]:
clean_df["Margin"] = (
    clean_df["Revenue"]
    - clean_df["Cost"]
)
clean_df["Margin_%"] = (
    clean_df["Margin"]
    / clean_df["Revenue"]
) * 100
clean_df[
    [
        "Units",
        "Cost_Price",
        "Selling_Price",
        "Revenue",
        "Cost",
        "Margin",
        "Margin_%"
    ]
].head(10)

,Units,Cost_Price,Selling_Price,Revenue,Cost,Margin,Margin_%
2,5,181.233170,208.980023,1044.900114,906.165848,138.734266,13.277275
3,2,195.811402,260.879960,521.759920,391.622805,130.137115,24.941953
4,3,23.571888,30.624472,91.873416,70.715665,21.157751,23.029242
5,4,12.599354,13.561234,54.244938,50.397415,3.847523,7.092869
7,4,20.903429,23.776089,95.104355,83.613716,11.490639,12.082137
14,5,186.326774,262.317500,1311.587500,931.633868,379.953633,28.968989
18,4,107.436518,112.953511,451.814042,429.746070,22.067972,4.884304
19,1,41.956742,45.969627,45.969627,41.956742,4.012885,8.729426
21,1,42.114525,50.383555,50.383555,42.114525,8.269030,16.412160
25,1,25.494853,36.134918,36.134918,25.494853,10.640065,29.445383

In [39]:
# Create date features

clean_df["Year"] = clean_df[
    "Invoice_Date"
].dt.year

clean_df["Month"] = clean_df[
    "Invoice_Date"
].dt.month

clean_df["Week"] = clean_df[
    "Invoice_Date"
].dt.isocalendar().week

clean_df["Day_Name"] = clean_df[
    "Invoice_Date"
].dt.day_name()

print("Date features created!")

Date features created!

In [40]:
clean_df[
    [
        "Invoice_Date",
        "Year",
        "Month",
        "Week",
        "Day_Name"
    ]
].head(10)

          Invoice_Date  Year  Month  Week   Day_Name
2  2024-08-26 22:03:00  2024      8    35     Monday
3  2024-06-09 04:34:00  2024      6    23     Sunday
4  2024-06-07 01:13:00  2024      6    23     Friday
5  2024-11-09 09:19:00  2024     11    45   Saturday
7  2024-09-11 12:57:00  2024      9    37  Wednesday
14 2024-09-18 21:06:00  2024      9    38  Wednesday
18 2024-11-02 12:12:00  2024     11    44   Saturday
19 2024-06-13 09:23:00  2024      6    24   Thursday
21 2024-05-15 08:11:00  2024      5    20  Wednesday
25 2024-08-23 00:16:00  2024      8    34     Friday

In [41]:
clean_df.to_csv(
    "../data/cleaned/cleaned_data.csv",
    index=False
)

print("Cleaned data saved!")

Cleaned data saved!

In [42]:
# Product-wise weekly sales

product_weekly = clean_df.groupby(
    [
        "Year",
        "Week",
        "Category",
        "Brand",
        "Product_Name"
    ]
).agg({
    "Units": "sum",
    "Revenue": "sum",
    "Margin": "sum",
    "Stock_On_Hand": "mean"
}).reset_index()

In [44]:
product_weekly.rename(
    columns={
        "Units": "Weekly_Units_Sold",
        "Revenue": "Weekly_Revenue",
        "Margin": "Weekly_Margin",
        "Stock_On_Hand":
        "Average_Stock"
    },
    inplace=True
)

In [45]:
product_weekly.head(20)

,Year,Week,Category,Brand,Product_Name,Weekly_Units_Sold,Weekly_Revenue,Weekly_Margin,Average_Stock
0,2024,1,Beverages,Nestle,Milo Drink,23,3115.820040,542.245932,294.833333
1,2024,1,Beverages,Nestle,Nescafe Coffee,41,5238.283596,981.603543,282.142857
2,2024,1,Beverages,PepsiCo,7UP Bottle,30,3536.617686,738.512623,285.900000
3,2024,1,Beverages,PepsiCo,Mountain Dew,22,1476.122835,245.921737,282.375000
4,2024,1,Beverages,PepsiCo,Pepsi 750ml,18,2708.075012,604.814030,279.500000
5,2024,1,Beverages,Tata,Tata Coffee,53,9492.699583,1987.396942,319.388889
6,2024,1,Beverages,Tata,Tata Tea,32,5035.873963,903.160372,306.833333
7,2024,1,Dairy,Amul,Amul Butter,20,2725.798894,652.340463,309.000000
8,2024,1,Dairy,Amul,Amul Cheese,35,4740.802780,1071.320695,255.083333
9,2024,1,Dairy,Amul,Amul Curd,34,3360.250230,578.677360,296.800000
10,2024,1,Dairy,Amul,Amul Milk,26,2903.832362,639.654979,332.700000
11,2024,1,Dairy,Nestle,Nestle Greek Yogurt,42,5412.974405,1153.342754,316.285714
12,2024,1,Dairy,Nestle,Nestle Milk Powder,34,4993.379627,1132.292008,256.666667
13,2024,1,Dairy,Nestle,Nestle Yogurt,57,7770.400517,1260.630270,216.058824
14,2024,1,Fruits,Tata,Apple Pack,48,5392.217612,956.356757,251.307692
15,2024,1,Fruits,Tata,Banana Pack,43,6197.083381,1020.634274,239.928571
16,2024,1,Fruits,Tata,Orange Pack,27,2967.131390,491.640019,269.800000
17,2024,1,Grocery,ITC,Aashirvaad Atta,50,4927.621150,1075.344812,272.687500
18,2024,1,Grocery,ITC,Sunfeast Pasta,68,8924.273129,1833.604868,250.192308
19,2024,1,Grocery,Tata,Tata Rice,21,3032.384426,577.699577,316.875000

In [ ]:
### Category-wise monthly sales

In [46]:
product_weekly.rename(
    columns={
        "Units": "Weekly_Units_Sold",
        "Revenue": "Weekly_Revenue",
        "Margin": "Weekly_Margin",
        "Stock_On_Hand":
        "Average_Stock"
    },
    inplace=True
)
product_weekly.head(20)

,Year,Week,Category,Brand,Product_Name,Weekly_Units_Sold,Weekly_Revenue,Weekly_Margin,Average_Stock
0,2024,1,Beverages,Nestle,Milo Drink,23,3115.820040,542.245932,294.833333
1,2024,1,Beverages,Nestle,Nescafe Coffee,41,5238.283596,981.603543,282.142857
2,2024,1,Beverages,PepsiCo,7UP Bottle,30,3536.617686,738.512623,285.900000
3,2024,1,Beverages,PepsiCo,Mountain Dew,22,1476.122835,245.921737,282.375000
4,2024,1,Beverages,PepsiCo,Pepsi 750ml,18,2708.075012,604.814030,279.500000
5,2024,1,Beverages,Tata,Tata Coffee,53,9492.699583,1987.396942,319.388889
6,2024,1,Beverages,Tata,Tata Tea,32,5035.873963,903.160372,306.833333
7,2024,1,Dairy,Amul,Amul Butter,20,2725.798894,652.340463,309.000000
8,2024,1,Dairy,Amul,Amul Cheese,35,4740.802780,1071.320695,255.083333
9,2024,1,Dairy,Amul,Amul Curd,34,3360.250230,578.677360,296.800000
10,2024,1,Dairy,Amul,Amul Milk,26,2903.832362,639.654979,332.700000
11,2024,1,Dairy,Nestle,Nestle Greek Yogurt,42,5412.974405,1153.342754,316.285714
12,2024,1,Dairy,Nestle,Nestle Milk Powder,34,4993.379627,1132.292008,256.666667
13,2024,1,Dairy,Nestle,Nestle Yogurt,57,7770.400517,1260.630270,216.058824
14,2024,1,Fruits,Tata,Apple Pack,48,5392.217612,956.356757,251.307692
15,2024,1,Fruits,Tata,Banana Pack,43,6197.083381,1020.634274,239.928571
16,2024,1,Fruits,Tata,Orange Pack,27,2967.131390,491.640019,269.800000
17,2024,1,Grocery,ITC,Aashirvaad Atta,50,4927.621150,1075.344812,272.687500
18,2024,1,Grocery,ITC,Sunfeast Pasta,68,8924.273129,1833.604868,250.192308
19,2024,1,Grocery,Tata,Tata Rice,21,3032.384426,577.699577,316.875000

### Create Category-wise Weekly Datase

In [48]:
category_weekly = clean_df.groupby(
    [
        "Year",
        "Week",
        "Category"
    ]
).agg({
    "Units": "sum",
    "Revenue": "sum",
    "Margin": "sum"
}).reset_index()
category_weekly = clean_df.groupby(
    [
        "Year",
        "Week",
        "Category"
    ]
).agg({
    "Units": "sum",
    "Revenue": "sum",
    "Margin": "sum"
}).reset_index()
category_weekly.head(20)

    Year  Week       Category  Units       Revenue        Margin
0   2024     1      Beverages    219  30603.492716   6003.655179
1   2024     1          Dairy    248  31907.438816   6488.258530
2   2024     1         Fruits    118  14556.432384   2468.631050
3   2024     1        Grocery    230  28314.679270   5544.340664
4   2024     1      Home Care    222  28800.758616   5722.155011
5   2024     1  Personal Care     57   8994.406902   1970.701350
6   2024     1         Snacks    436  59170.429111  11552.970721
7   2024     1     Vegetables    121  16048.976146   3197.692107
8   2024     2      Beverages    293  39794.410792   7725.009123
9   2024     2          Dairy    182  23897.445361   4847.976931
10  2024     2         Fruits     80   9044.642259   1894.969779
11  2024     2        Grocery    185  23960.592041   4973.760696
12  2024     2      Home Care    154  19862.412418   3885.333252
13  2024     2  Personal Care    102  13927.911255   3026.605917
14  2024     2         Snacks    402  50660.704429   9689.346657
15  2024     2     Vegetables     76   7509.038171   1537.535734
16  2024     3      Beverages    303  41183.954544   8232.260917
17  2024     3          Dairy    161  19498.831048   4056.484846
18  2024     3         Fruits     52   6140.035633   1333.575252
19  2024     3        Grocery    186  27147.575948   5461.773719

In [49]:
product_weekly.to_csv(
    "../data/cleaned/product_weekly.csv",
    index=False
)

category_weekly.to_csv(
    "../data/cleaned/category_weekly.csv",
    index=False
)

print("Weekly datasets saved!")

Weekly datasets saved!

In [50]:
product_weekly = product_weekly.sort_values(
    by=[
        "Product_Name",
        "Year",
        "Week"
    ]
)

In [51]:
# Previous week sales
product_weekly["Lag_1"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(1)
)

# Previous 2 weeks
product_weekly["Lag_2"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(2)
)

# Previous 3 weeks
product_weekly["Lag_3"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(3)
)

In [52]:
product_weekly[
    "Rolling_4_Week_Avg"
] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .transform(
        lambda x:
        x.rolling(4).mean()
    )
)

In [55]:
product_weekly[
    [
        "Product_Name",
        "Week",
        "Weekly_Units_Sold",
        "Lag_1",
        "Lag_2",
        "Lag_3",
        "Rolling_4_Week_Avg"
    ]
].head(20)

,Product_Name,Week,Weekly_Units_Sold,Lag_1,Lag_2,Lag_3,Rolling_4_Week_Avg
164,50-50 Biscuit,4,33,29.0,24.0,40.0,31.50
209,50-50 Biscuit,5,15,33.0,29.0,24.0,25.25
254,50-50 Biscuit,6,38,15.0,33.0,29.0,28.75
299,50-50 Biscuit,7,34,38.0,15.0,33.0,30.00
344,50-50 Biscuit,8,15,34.0,38.0,15.0,25.50
389,50-50 Biscuit,9,28,15.0,34.0,38.0,28.75
434,50-50 Biscuit,10,33,28.0,15.0,34.0,27.50
479,50-50 Biscuit,11,30,33.0,28.0,15.0,26.50
524,50-50 Biscuit,12,17,30.0,33.0,28.0,27.00
569,50-50 Biscuit,13,46,17.0,30.0,33.0,31.50
614,50-50 Biscuit,14,33,46.0,17.0,30.0,31.50
659,50-50 Biscuit,15,18,33.0,46.0,17.0,28.50
704,50-50 Biscuit,16,27,18.0,33.0,46.0,31.00
749,50-50 Biscuit,17,16,27.0,18.0,33.0,23.50
794,50-50 Biscuit,18,34,16.0,27.0,18.0,23.75
839,50-50 Biscuit,19,13,34.0,16.0,27.0,22.50
884,50-50 Biscuit,20,54,13.0,34.0,16.0,29.25
929,50-50 Biscuit,21,19,54.0,13.0,34.0,30.00
974,50-50 Biscuit,22,25,19.0,54.0,13.0,27.75
1019,50-50 Biscuit,23,25,25.0,19.0,54.0,30.75

In [56]:
product_weekly = (
    product_weekly.dropna()
)
product_weekly[
    [
        "Product_Name",
        "Week",
        "Weekly_Units_Sold",
        "Lag_1",
        "Lag_2",
        "Lag_3",
        "Rolling_4_Week_Avg"
    ]
].head(20)
product_weekly.shape

(2205, 13)

In [57]:
product_weekly.to_csv(
    "../data/cleaned/final_forecasting_data.csv",
    index=False
)

print("Forecasting dataset saved!")

Forecasting dataset saved!

In [58]:
product_weekly.head()
product_weekly.shape

(2205, 13)

In [59]:
product_weekly.head()

,Year,Week,Category,Brand,Product_Name,Weekly_Units_Sold,Weekly_Revenue,Weekly_Margin,Average_Stock,Lag_1,Lag_2,Lag_3,Rolling_4_Week_Avg
164,2024,4,Snacks,Britannia,50-50 Biscuit,33,4875.216339,1046.740969,287.181818,29.0,24.0,40.0,31.50
209,2024,5,Snacks,Britannia,50-50 Biscuit,15,2570.843352,657.733087,247.714286,33.0,29.0,24.0,25.25
254,2024,6,Snacks,Britannia,50-50 Biscuit,38,4038.325633,586.422620,303.666667,15.0,33.0,29.0,28.75
299,2024,7,Snacks,Britannia,50-50 Biscuit,34,5149.104917,1119.908827,228.600000,38.0,15.0,33.0,30.00
344,2024,8,Snacks,Britannia,50-50 Biscuit,15,1465.058151,323.102985,296.000000,34.0,38.0,15.0,25.50

In [61]:
# Sort data properly
product_weekly = product_weekly.sort_values(
    by=[
        "Product_Name",
        "Year",
        "Week"
    ]
)

# Create next week's target
product_weekly["Target"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(-1)
)

print("Target created successfully!")
product_weekly[
    [
        "Product_Name",
        "Week",
        "Weekly_Units_Sold",
        "Target"
    ]
].head(20)

Target created successfully!

       Product_Name  Week  Weekly_Units_Sold  Target
164   50-50 Biscuit     4                 33    15.0
209   50-50 Biscuit     5                 15    38.0
254   50-50 Biscuit     6                 38    34.0
299   50-50 Biscuit     7                 34    15.0
344   50-50 Biscuit     8                 15    28.0
389   50-50 Biscuit     9                 28    33.0
434   50-50 Biscuit    10                 33    30.0
479   50-50 Biscuit    11                 30    17.0
524   50-50 Biscuit    12                 17    46.0
569   50-50 Biscuit    13                 46    33.0
614   50-50 Biscuit    14                 33    18.0
659   50-50 Biscuit    15                 18    27.0
704   50-50 Biscuit    16                 27    16.0
749   50-50 Biscuit    17                 16    34.0
794   50-50 Biscuit    18                 34    13.0
839   50-50 Biscuit    19                 13    54.0
884   50-50 Biscuit    20                 54    19.0
929   50-50 Biscuit    21                 19    25.0
974   50-50 Biscuit    22                 25    25.0
1019  50-50 Biscuit    23                 25    20.0

In [62]:
product_weekly = (
    product_weekly.dropna()
)

print(product_weekly.shape)

(2160, 14)

In [63]:
features = [
    "Week",
    "Month",
    "Weekly_Revenue",
    "Weekly_Margin",
    "Average_Stock",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Rolling_4_Week_Avg"
]

X = product_weekly[features]

print(X.head())

KeyError: "['Month'] not in index"

In [64]:
product_weekly = clean_df.groupby(
    [
        "Year",
        "Month",
        "Week",
        "Category",
        "Brand",
        "Product_Name"
    ]
).agg({
    "Units": "sum",
    "Revenue": "sum",
    "Margin": "sum",
    "Stock_On_Hand": "mean"
}).reset_index()

In [65]:
product_weekly.rename(
    columns={
        "Units": "Weekly_Units_Sold",
        "Revenue": "Weekly_Revenue",
        "Margin": "Weekly_Margin",
        "Stock_On_Hand":
        "Average_Stock"
    },
    inplace=True
)

In [66]:
product_weekly = product_weekly.sort_values(
    by=[
        "Product_Name",
        "Year",
        "Week"
    ]
)

product_weekly["Lag_1"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(1)
)

product_weekly["Lag_2"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(2)
)

product_weekly["Lag_3"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(3)
)

product_weekly[
    "Rolling_4_Week_Avg"
] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .transform(
        lambda x:
        x.rolling(4).mean()
    )
)

product_weekly = (
    product_weekly.dropna()
)

In [67]:
product_weekly["Target"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(-1)
)

product_weekly = (
    product_weekly.dropna()
)

print(product_weekly.shape)

(2559, 15)

In [68]:
features = [
    "Week",
    "Month",
    "Weekly_Revenue",
    "Weekly_Margin",
    "Average_Stock",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Rolling_4_Week_Avg"
]

X = product_weekly[features]

print(X.head())

     Week  Month  Weekly_Revenue  Weekly_Margin  Average_Stock  Lag_1  Lag_2  \
119     3      1     3717.208706     855.534369     365.800000   24.0   10.0
164     4      1     4875.216339    1046.740969     287.181818   29.0   24.0
209     5      1      496.741381     114.093006     230.333333   33.0   29.0
254     5      2     2074.101971     543.640081     260.750000    4.0   33.0
299     6      2     4038.325633     586.422620     303.666667   11.0    4.0

     Lag_3  Rolling_4_Week_Avg
119   30.0               23.25
164   10.0               24.00
209   24.0               22.50
254   29.0               19.25
299   33.0               21.50

In [69]:
product_weekly.isnull().sum()

Year                  0
Month                 0
Week                  0
Category              0
Brand                 0
Product_Name          0
Weekly_Units_Sold     0
Weekly_Revenue        0
Weekly_Margin         0
Average_Stock         0
Lag_1                 0
Lag_2                 0
Lag_3                 0
Rolling_4_Week_Avg    0
Target                0
dtype: int64

In [70]:
print(product_weekly.columns)

Index(['Year', 'Month', 'Week', 'Category', 'Brand', 'Product_Name',
       'Weekly_Units_Sold', 'Weekly_Revenue', 'Weekly_Margin', 'Average_Stock',
       'Lag_1', 'Lag_2', 'Lag_3', 'Rolling_4_Week_Avg', 'Target'],
      dtype='str')

In [71]:
features = [
    "Week",
    "Month",
    "Weekly_Revenue",
    "Weekly_Margin",
    "Average_Stock",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Rolling_4_Week_Avg"
]

X = product_weekly[features]

print(X.head())

     Week  Month  Weekly_Revenue  Weekly_Margin  Average_Stock  Lag_1  Lag_2  \
119     3      1     3717.208706     855.534369     365.800000   24.0   10.0
164     4      1     4875.216339    1046.740969     287.181818   29.0   24.0
209     5      1      496.741381     114.093006     230.333333   33.0   29.0
254     5      2     2074.101971     543.640081     260.750000    4.0   33.0
299     6      2     4038.325633     586.422620     303.666667   11.0    4.0

     Lag_3  Rolling_4_Week_Avg
119   30.0               23.25
164   10.0               24.00
209   24.0               22.50
254   29.0               19.25
299   33.0               21.50

In [72]:
y = product_weekly["Target"]

print(y.head())

119    33.0
164     4.0
209    11.0
254    38.0
299    34.0
Name: Target, dtype: float64

# FreshMart - FMCG Forecasting & Inventory Management

In [78]:
import pandas as pd
df = pd.read_csv("../data/cleaned/final_forecasting_data.csv")
df.head()
df.info()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 2205 entries, 0 to 2204
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                2205 non-null   int64
 1   Week                2205 non-null   int64
 2   Category            2205 non-null   str
 3   Brand               2205 non-null   str
 4   Product_Name        2205 non-null   str
 5   Weekly_Units_Sold   2205 non-null   int64
 6   Weekly_Revenue      2205 non-null   float64
 7   Weekly_Margin       2205 non-null   float64
 8   Average_Stock       2205 non-null   float64
 9   Lag_1               2205 non-null   float64
 10  Lag_2               2205 non-null   float64
 11  Lag_3               2205 non-null   float64
 12  Rolling_4_Week_Avg  2205 non-null   float64
dtypes: float64(7), int64(3), str(3)
memory usage: 224.1 KB

Index(['Year', 'Week', 'Category', 'Brand', 'Product_Name',
       'Weekly_Units_Sold', 'Weekly_Revenue', 'Weekly_Margin', 'Average_Stock',
       'Lag_1', 'Lag_2', 'Lag_3', 'Rolling_4_Week_Avg'],
      dtype='str')

In [79]:
product_weekly = (
    product_weekly.reset_index(drop=True)
)

print(product_weekly.head())

   Year  Month  Week Category      Brand   Product_Name  Weekly_Units_Sold  \
0  2024      1     3   Snacks  Britannia  50-50 Biscuit                 29
1  2024      1     4   Snacks  Britannia  50-50 Biscuit                 33
2  2024      1     5   Snacks  Britannia  50-50 Biscuit                  4
3  2024      2     5   Snacks  Britannia  50-50 Biscuit                 11
4  2024      2     6   Snacks  Britannia  50-50 Biscuit                 38

   Weekly_Revenue  Weekly_Margin  Average_Stock  Lag_1  Lag_2  Lag_3  \
0     3717.208706     855.534369     365.800000   24.0   10.0   30.0
1     4875.216339    1046.740969     287.181818   29.0   24.0   10.0
2      496.741381     114.093006     230.333333   33.0   29.0   24.0
3     2074.101971     543.640081     260.750000    4.0   33.0   29.0
4     4038.325633     586.422620     303.666667   11.0    4.0   33.0

   Rolling_4_Week_Avg  Target
0               23.25    33.0
1               24.00     4.0
2               22.50    11.0
3               19.25    38.0
4               21.50    34.0

In [80]:
category_weekly = (
    category_weekly.reset_index(drop=True)
)

In [81]:
product_weekly.head()

,Year,Month,Week,Category,Brand,Product_Name,Weekly_Units_Sold,Weekly_Revenue,Weekly_Margin,Average_Stock,Lag_1,Lag_2,Lag_3,Rolling_4_Week_Avg,Target
0,2024,1,3,Snacks,Britannia,50-50 Biscuit,29,3717.208706,855.534369,365.800000,24.0,10.0,30.0,23.25,33.0
1,2024,1,4,Snacks,Britannia,50-50 Biscuit,33,4875.216339,1046.740969,287.181818,29.0,24.0,10.0,24.00,4.0
2,2024,1,5,Snacks,Britannia,50-50 Biscuit,4,496.741381,114.093006,230.333333,33.0,29.0,24.0,22.50,11.0
3,2024,2,5,Snacks,Britannia,50-50 Biscuit,11,2074.101971,543.640081,260.750000,4.0,33.0,29.0,19.25,38.0
4,2024,2,6,Snacks,Britannia,50-50 Biscuit,38,4038.325633,586.422620,303.666667,11.0,4.0,33.0,21.50,34.0

In [86]:
!pip install  numpy openpyxl matplotlib scikit-learn xgboost

^C

In [87]:
from sklearn.model_selection import (
    train_test_split
)

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )
)

print(X_train.shape)
print(X_test.shape)

(2047, 9)
(512, 9)

Requirement already satisfied: numpy in c:\Users\user\DFIM project\.venv\Lib\site-packages (2.4.6)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting xgboost
  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 1.2 MB/s eta 0:00:08
   -- ------------------------------------- 0.5/9.5 MB 1.2 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.5 MB 719.4 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.5 MB 719.4 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.5 MB 719.4 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.5 MB 719.4 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/9.5 MB 719.4 kB/s eta 0:00:13
   ---- ----------------------------------- 1.0/9.5 MB 455.5 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.5 MB 455.5 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.5 MB 455.5 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.5 MB 445.3 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.5 MB 445.3 kB/s eta 0:00:19
   ------ --------------------------------- 1.6/9.5 MB 470.1 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.5 MB 470.1 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.5 MB 470.1 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.5 MB 470.1 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.5 MB 449.3 kB/s eta 0:00:18
   ------- -------------------------------- 1.8/9.5 MB 449.3 kB/s eta 0:00:18
   ------- -------------------------------- 1.8/9.5 MB 449.3 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.5 MB 429.5 kB/s eta 0:00:18
   -------- ------------------------------- 2.1/9.5 MB 429.5 kB/s eta 0:00:18
   --------- ------------------------------ 2.4/9.5 MB 458.5 kB/s eta 0:00:16
   --------- ------------------------------ 2.4/9.5 MB 458.5 kB/s eta 0:00:16
   ----------- ---------------------------- 2.6/9.5 MB 474.0 kB/s eta 0:00:15
   ----------- ---------------------------- 2.6/9.5 MB 474.0 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.5 MB 485.5 kB/s eta 0:00:14
   ------------ --------------------------- 2.9/9.5 MB 485.5 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.5 MB 486.8 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.5 MB 486.8 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.5 MB 486.8 kB/s eta 0:00:14
   -------------- ------------------------- 3.4/9.5 MB 494.6 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.5 MB 507.6 kB/s eta 0:00:12
   --------------- ------------------------ 3.7/9.5 MB 507.6 kB/s eta 0:00:12
   --------------- ------------------------ 3.7/9.5 MB 507.6 kB/s eta 0:00:12
   ---------------- ----------------------- 3.9/9.5 MB 505.5 kB/s eta 0:00:11
   ----------------- ---------------------- 4.2/9.5 MB 525.8 kB/s eta 0:00:11
   ----------------- ---------------------- 4.2/9.5 MB 525.8 kB/s eta 0:00:11
   ------------------ --------------------- 4.5/9.5 MB 533.3 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.5 MB 533.3 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.5 MB 533.3 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.5 MB 533.3 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.5 MB 533.3 kB/s eta 0:00:10
   ------------------ --------------------- 4.5/9.5 MB 533.3 kB/s eta 0:00:10
   --------------------- ------------------ 5.0/9.5 MB 520.4 kB/s eta 0:00:09
   ---------------------- ----------------- 5.2/9.5 MB 530.3 kB/s eta 0:00:08
   ---------------------- ----------------- 5.2/9.5 MB 530.3 kB/s eta 0:00:08
   ----------------------- ---------------- 5.5/9.5 MB 537.1 kB/s eta 0:00:08
   ----------------------- ---------------- 5.5/9.5 MB 537.1 kB/s eta 0:00:08
   ------------------------ --------------- 5.8/9.5 MB 542.2 kB/s eta 0:00:07
   ------------------------ --------------- 5.8/9.5 MB 542.2 kB/s eta 0:00:07
   ------------------------ --------------- 5.8/9.5 MB 542.2 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.0/9.5 MB 533.0 kB/s eta 0:00:07
   -------------------------- ------------- 6.3/9.5 MB 478.9 kB/s eta 0:00:07
   -------------------------- ------------- 6.3/9.5 MB 478.9 kB/s eta 0:00:07
   --------------------------- ------------ 6.6/9.5 MB 484.0 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.5 MB 492.6 kB/s eta 0:00:06
   ---------------------------- ----------- 6.8/9.5 MB 492.6 kB/s eta 0:00:06
   ---------------------------- ----------- 6.8/9.5 MB 492.6 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.5 MB 488.6 kB/s eta 0:00:05
   ----------------------------- ---------- 7.1/9.5 MB 488.6 kB/s eta 0:00:05
   ----------------------------- ---------- 7.1/9.5 MB 488.6 kB/s eta 0:00:05
   ------------------------------ --------- 7.3/9.5 MB 490.4 kB/s eta 0:00:05
   ------------------------------ --------- 7.3/9.5 MB 490.4 kB/s eta 0:00:05
   ------------------------------ --------- 7.3/9.5 MB 490.4 kB/s eta 0:00:05
   -------------------------------- ------- 7.6/9.5 MB 488.9 kB/s eta 0:00:04
   -------------------------------- ------- 7.6/9.5 MB 488.9 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.5 MB 492.3 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.5 MB 461.8 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.5 MB 474.1 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.5 MB 474.1 kB/s eta 0:00:03
   ------------------------------------ --- 8.7/9.5 MB 474.1 kB/s eta 0:00:02
   ------------------------------------ --- 8.7/9.5 MB 474.1 kB/s eta 0:00:02
   ------------------------------------ --- 8.7/9.5 MB 474.1 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 472.4 kB/s eta 0:00:02
   ------------------------------------- -- 8.9/9.5 MB 472.4 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.5 MB 479.3 kB/s eta 0:00:01
   -------------------------------------- - 9.2/9.5 MB 479.3 kB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 481.1 kB/s  0:00:19
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 248.7 kB/s eta 0:00:32
   -- ------------------------------------- 0.5/8.3 MB 248.7 kB/s eta 0:00:32
   -- ------------------------------------- 0.5/8.3 MB 248.7 kB/s eta 0:00:32
   -- ------------------------------------- 0.5/8.3 MB 248.7 kB/s eta 0:00:32
   -- ------------------------------------- 0.5/8.3 MB 248.7 kB/s eta 0:00:32
   -- ------------------------------------- 0.5/8.3 MB 248.7 kB/s eta 0:00:32
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   --- ------------------------------------ 0.8/8.3 MB 224.6 kB/s eta 0:00:34
   ----- ---------------------------------- 1.0/8.3 MB 214.1 kB/s eta 0:00:34
   ----- ---------------------------------- 1.0/8.3 MB 214.1 kB/s eta 0:00:34
   ----- ---------------------------------- 1.0/8.3 MB 214.1 kB/s eta 0:00:34
   ------ --------------------------------- 1.3/8.3 MB 243.8 kB/s eta 0:00:29
   ------ --------------------------------- 1.3/8.3 MB 243.8 kB/s eta 0:00:29
   ------ --------------------------------- 1.3/8.3 MB 243.8 kB/s eta 0:00:29
   ------- -------------------------------- 1.6/8.3 MB 266.5 kB/s eta 0:00:26
   ------- -------------------------------- 1.6/8.3 MB 266.5 kB/s eta 0:00:26
   ------- -------------------------------- 1.6/8.3 MB 266.5 kB/s eta 0:00:26
   -------- ------------------------------- 1.8/8.3 MB 282.0 kB/s eta 0:00:23
   -------- ------------------------------- 1.8/8.3 MB 282.0 kB/s eta 0:00:23
   -------- ------------------------------- 1.8/8.3 MB 282.0 kB/s eta 0:00:23
   ---------- ----------------------------- 2.1/8.3 MB 290.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.1/8.3 MB 290.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.1/8.3 MB 290.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.1/8.3 MB 290.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.1/8.3 MB 290.3 kB/s eta 0:00:22
   ----------- ---------------------------- 2.4/8.3 MB 289.8 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.3 MB 289.8 kB/s eta 0:00:21
   ------------ --------------------------- 2.6/8.3 MB 302.9 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.3 MB 302.9 kB/s eta 0:00:19
   ------------ --------------------------- 2.6/8.3 MB 302.9 kB/s eta 0:00:19
   ------------- -------------------------- 2.9/8.3 MB 318.6 kB/s eta 0:00:17
   ------------- -------------------------- 2.9/8.3 MB 318.6 kB/s eta 0:00:17
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.3 MB 327.3 kB/s eta 0:00:16
   ---------------- ----------------------- 3.4/8.3 MB 297.8 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.3 MB 297.8 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.3 MB 297.8 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.3 MB 297.8 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.3 MB 297.8 kB/s eta 0:00:17
   ---------------- ----------------------- 3.4/8.3 MB 297.8 kB/s eta 0:00:17
   ----------------- ---------------------- 3.7/8.3 MB 289.2 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.3 MB 289.2 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.3 MB 289.2 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.3 MB 289.2 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.3 MB 289.2 kB/s eta 0:00:16
   ----------------- ---------------------- 3.7/8.3 MB 289.2 kB/s eta 0:00:16
   ------------------ --------------------- 3.9/8.3 MB 282.3 kB/s eta 0:00:16
   ------------------ --------------------- 3.9/8.3 MB 282.3 kB/s eta 0:00:16
   ------------------ --------------------- 3.9/8.3 MB 282.3 kB/s eta 0:00:16
   ------------------ --------------------- 3.9/8.3 MB 282.3 kB/s eta 0:00:16
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   -------------------- ------------------- 4.2/8.3 MB 283.8 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   --------------------- ------------------ 4.5/8.3 MB 268.5 kB/s eta 0:00:15
   ---------------------- ----------------- 4.7/8.3 MB 260.2 kB/s eta 0:00:14
   ---------------------- ----------------- 4.7/8.3 MB 260.2 kB/s eta 0:00:14
   ---------------------- ----------------- 4.7/8.3 MB 260.2 kB/s eta 0:00:14
   ---------------------- ----------------- 4.7/8.3 MB 260.2 kB/s eta 0:00:14
   ---------------------- ----------------- 4.7/8.3 MB 260.2 kB/s eta 0:00:14
   ---------------------- ----------------- 4.7/8.3 MB 260.2 kB/s eta 0:00:14
   ------------------------ --------------- 5.0/8.3 MB 255.1 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.3 MB 255.1 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.3 MB 255.1 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.3 MB 255.1 kB/s eta 0:00:13
   ------------------------- -------------- 5.2/8.3 MB 258.8 kB/s eta 0:00:12
   ------------------------- -------------- 5.2/8.3 MB 258.8 kB/s eta 0:00:12
   ------------------------- -------------- 5.2/8.3 MB 258.8 kB/s eta 0:00:12
   ------------------------- -------------- 5.2/8.3 MB 258.8 kB/s eta 0:00:12
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   -------------------------- ------------- 5.5/8.3 MB 261.3 kB/s eta 0:00:11
   --------------------------- ------------ 5.8/8.3 MB 254.0 kB/s eta 0:00:10
   --------------------------- ------------ 5.8/8.3 MB 254.0 kB/s eta 0:00:10
   --------------------------- ------------ 5.8/8.3 MB 254.0 kB/s eta 0:00:10
   --------------------------- ------------ 5.8/8.3 MB 254.0 kB/s eta 0:00:10
   --------------------------- ------------ 5.8/8.3 MB 254.0 kB/s eta 0:00:10
   ----------------------------- ---------- 6.0/8.3 MB 252.7 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.3 MB 252.7 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.3 MB 252.7 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.3 MB 252.7 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.3 MB 252.7 kB/s eta 0:00:09
   ----------------------------- ---------- 6.0/8.3 MB 252.7 kB/s eta 0:00:09
   ------------------------------ --------- 6.3/8.3 MB 251.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.3 MB 251.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.3 MB 251.5 kB/s eta 0:00:08
   ------------------------------ --------- 6.3/8.3 MB 251.5 kB/s eta 0:00:08
   ------------------------------- -------- 6.6/8.3 MB 252.3 kB/s eta 0:00:07
   ------------------------------- -------- 6.6/8.3 MB 252.3 kB/s eta 0:00:07
   ------------------------------- -------- 6.6/8.3 MB 252.3 kB/s eta 0:00:07
   -------------------------------- ------- 6.8/8.3 MB 256.6 kB/s eta 0:00:06
   -------------------------------- ------- 6.8/8.3 MB 256.6 kB/s eta 0:00:06
   -------------------------------- ------- 6.8/8.3 MB 256.6 kB/s eta 0:00:06
   -------------------------------- ------- 6.8/8.3 MB 256.6 kB/s eta 0:00:06
   ---------------------------------- ----- 7.1/8.3 MB 260.1 kB/s eta 0:00:05

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [88]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

print("Model trained successfully!")

Model trained successfully!

In [89]:
predictions = model.predict(
    X_test
)

print(predictions[:10])

[24.982248 26.345945 26.313738 33.00045  26.017378 31.544104 29.40777
 15.254082 37.55751  24.648945]

In [90]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(
    y_test,
    predictions
)

rmse = (
    mean_squared_error(
        y_test,
        predictions
    )
) ** 0.5

r2 = r2_score(
    y_test,
    predictions
)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 10.069599023088813
RMSE: 12.550192335004075
R2 Score: 0.38152229134399995

In [91]:
from sklearn.preprocessing import (
    LabelEncoder
)

product_encoder = LabelEncoder()

product_weekly[
    "Product_Encoded"
] = product_encoder.fit_transform(
    product_weekly["Product_Name"]
)

print("Product encoding completed!")

Product encoding completed!

In [92]:
# Lag 4
product_weekly["Lag_4"] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .shift(4)
)

# Rolling 8 week average
product_weekly[
    "Rolling_8_Week_Avg"
] = (
    product_weekly.groupby(
        "Product_Name"
    )["Weekly_Units_Sold"]
    .transform(
        lambda x:
        x.rolling(8).mean()
    )
)

In [93]:
product_weekly = (
    product_weekly.dropna()
)

print(product_weekly.shape)

(2244, 18)

In [94]:
features = [
    "Product_Encoded",
    "Week",
    "Month",
    "Weekly_Revenue",
    "Weekly_Margin",
    "Average_Stock",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Lag_4",
    "Rolling_4_Week_Avg",
    "Rolling_8_Week_Avg"
]

X = product_weekly[features]

y = product_weekly["Target"]

In [101]:
from sklearn.model_selection import (
    train_test_split
)

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )
)

print(X_train.shape)
print(X_test.shape)

(1795, 14)
(449, 14)

In [102]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=7,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

print("Improved model trained!")

Improved model trained!

In [103]:
predictions = model.predict(
    X_test
)

print(predictions[:10])

[30.434782 33.396107 38.13058  17.922304 30.503235 44.48143  28.833897
 25.654625 19.856726 30.075953]

In [104]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(
    y_test,
    predictions
)

rmse = (
    mean_squared_error(
        y_test,
        predictions
    )
) ** 0.5

r2 = r2_score(
    y_test,
    predictions
)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 9.550918374135925
RMSE: 12.463707410563183
R2 Score: 0.4318216766569559

In [99]:
from sklearn.preprocessing import (
    LabelEncoder
)

category_encoder = LabelEncoder()
brand_encoder = LabelEncoder()

product_weekly[
    "Category_Encoded"
] = category_encoder.fit_transform(
    product_weekly["Category"]
)

product_weekly[
    "Brand_Encoded"
] = brand_encoder.fit_transform(
    product_weekly["Brand"]
)

print("Encoding completed!")

Encoding completed!

In [100]:
features = [
    "Product_Encoded",
    "Category_Encoded",
    "Brand_Encoded",
    "Week",
    "Month",
    "Weekly_Revenue",
    "Weekly_Margin",
    "Average_Stock",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Lag_4",
    "Rolling_4_Week_Avg",
    "Rolling_8_Week_Avg"
]

X = product_weekly[features]
y = product_weekly["Target"]

In [105]:
product_weekly.to_csv(
    "../data/cleaned/final_product_forecasting.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [106]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from statsmodels) (2.4.6)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from statsmodels) (1.17.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from statsmodels) (3.0.3)
Collecting patsy>=0.5.6 (from statsmodels)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from statsmodels) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\user\DFIM project\.venv\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\user\DFIM project\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.6 MB 4.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.6 MB 5.5 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.6 MB 5.3 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.6 MB 5.2 MB/s eta 0:00:02
   ------------------------- -------------- 6.0/9.6 MB 6.1 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.6 MB 6.1 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.6 MB 6.1 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.6 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 5.1 MB/s  0:00:02
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Installing collected packages: patsy, statsmodels

   ---------------------------------------- 0/2 [patsy]
   ---------------------------------------- 0/2 [patsy]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   -------------------- ------------------- 1/2 [statsmodels]
   ---------------------------------------- 2/2 [statsmodels]

Successfully installed patsy-1.0.2 statsmodels-0.14.6

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [107]:
print(
    category_weekly["Category"]
    .unique()
)

<StringArray>
[    'Beverages',         'Dairy',        'Fruits',       'Grocery',
     'Home Care', 'Personal Care',        'Snacks',    'Vegetables']
Length: 8, dtype: str

In [108]:
snacks_data = category_weekly[
    category_weekly["Category"]
    == "Snacks"
]

snacks_data = snacks_data.sort_values(
    by=["Year", "Week"]
)

print(snacks_data.head())

    Year  Week Category  Units       Revenue        Margin
6   2024     1   Snacks    436  59170.429111  11552.970721
14  2024     2   Snacks    402  50660.704429   9689.346657
22  2024     3   Snacks    355  43227.599287   7782.038360
30  2024     4   Snacks    357  46641.579752   9659.240860
38  2024     5   Snacks    402  56877.825903  11439.942220

In [113]:
category_weekly = (
    category_weekly.sort_values(
        by=[
            "Category",
            "Year",
            "Week"
        ]
    )
)

In [115]:
print(category_weekly.columns)

Index(['Year', 'Week', 'Category', 'Units', 'Revenue', 'Margin'], dtype='str')

In [116]:
category_weekly.rename(
    columns={
        "Units":
        "Weekly_Units_Sold",

        "Revenue":
        "Weekly_Revenue",

        "Margin":
        "Weekly_Margin"
    },
    inplace=True
)

print(category_weekly.columns)

Index(['Year', 'Week', 'Category', 'Weekly_Units_Sold', 'Weekly_Revenue',
       'Weekly_Margin'],
      dtype='str')

In [159]:
category_weekly["Lag_1"] = (
    category_weekly.groupby(
        "Category"
    )["Weekly_Units_Sold"]
    .shift(1)
)

category_weekly["Lag_2"] = (
    category_weekly.groupby(
        "Category"
    )["Weekly_Units_Sold"]
    .shift(2)
)

category_weekly["Lag_3"] = (
    category_weekly.groupby(
        "Category"
    )["Weekly_Units_Sold"]
    .shift(3)
)


print("Lag features created!")

Lag features created!

In [160]:
category_weekly[
    "Rolling_4_Week_Avg"
] = (
    category_weekly.groupby(
        "Category"
    )["Weekly_Units_Sold"]
    .transform(
        lambda x:
        x.rolling(4).mean()
    )
)

print("Rolling average created!")

Rolling average created!

In [161]:
category_weekly["Target"] = (
    category_weekly.groupby(
        "Category"
    )["Weekly_Units_Sold"]
    .shift(-1)
)

print("Target created!")

Target created!

In [162]:
category_weekly = (
    category_weekly.dropna()
)

category_weekly = (
    category_weekly.reset_index(
        drop=True
    )
)

print(category_weekly.shape)

(288, 15)

In [163]:
from sklearn.preprocessing import (
    LabelEncoder
)

category_encoder = (
    LabelEncoder()
)

category_weekly[
    "Category_Encoded"
] = (
    category_encoder.fit_transform(
        category_weekly[
            "Category"
        ]
    )
)

print("Category encoded!")

Category encoded!

In [164]:
features = [
    "Category_Encoded",
    "Week",
    "Weekly_Revenue",
    "Weekly_Margin",
    "Lag_1",
    "Lag_2",
    "Lag_3",
    "Rolling_4_Week_Avg"
]

X = category_weekly[
    features
]

y = category_weekly[
    "Target"
]

print(X.head())
print(y.head())

   Category_Encoded  Week  Weekly_Revenue  Weekly_Margin  Lag_1  Lag_2  Lag_3  \
0                 0    14    45217.848937    9393.556246  250.0  316.0  210.0
1                 0    15    35841.008057    7409.004661  315.0  250.0  316.0
2                 0    16    30945.537137    6483.319678  249.0  315.0  250.0
3                 0    17    49627.596464   10124.703159  238.0  249.0  315.0
4                 0    18    31942.615438    6715.385333  370.0  238.0  249.0

   Rolling_4_Week_Avg
0              272.75
1              282.50
2              263.00
3              293.00
4              283.00
0    249.0
1    238.0
2    370.0
3    275.0
4    280.0
Name: Target, dtype: float64

In [165]:
from sklearn.model_selection import (
    train_test_split
)

X_train, X_test, y_train, y_test = (
    train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )
)

print(X_train.shape)
print(X_test.shape)

(230, 8)
(58, 8)

In [166]:
from xgboost import XGBRegressor

category_model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

category_model.fit(
    X_train,
    y_train
)

print("Category model trained!")

Category model trained!

In [168]:
predictions = category_model.predict(
    X_test
)

print(predictions[:10])

[178.83481 181.6671  111.84809 178.67215  84.83481 280.44196 174.79176
 185.07918  96.32343  96.08542]

In [170]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(
    y_test,
    predictions
)

rmse = (
    mean_squared_error(
        y_test,
        predictions
    )
) ** 0.5

r2 = r2_score(
    y_test,
    predictions
)

print("MAE:", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 24.417558341190734
RMSE: 33.03229623831252
R2 Score: 0.8513732317295013

In [127]:
category_weekly.to_csv(
    "../data/cleaned/final_category_forecasting.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [128]:
def predict_category(category_name):

    # Filter category data
    category_data = category_weekly[
        category_weekly["Category"]
        == category_name
    ]

    # Get latest row
    latest_row = category_data.iloc[-1]

    # Encode category
    encoded_category = (
        category_encoder.transform(
            [category_name]
        )[0]
    )

    # Create input dataframe
    input_data = pd.DataFrame({
        "Category_Encoded":
        [encoded_category],

        "Week":
        [latest_row["Week"]],

        "Weekly_Revenue":
        [latest_row["Weekly_Revenue"]],

        "Weekly_Margin":
        [latest_row["Weekly_Margin"]],

        "Lag_1":
        [latest_row["Lag_1"]],

        "Lag_2":
        [latest_row["Lag_2"]],

        "Lag_3":
        [latest_row["Lag_3"]],

        "Rolling_4_Week_Avg":
        [latest_row[
            "Rolling_4_Week_Avg"
        ]]
    })

    # Predict
    prediction = (
        category_model.predict(
            input_data
        )[0]
    )

    print(
        f"Predicted next week demand for {category_name}: "
        f"{round(prediction)} units"
    )

In [129]:
predict_category("Snacks")

Predicted next week demand for Snacks: 357 units

In [130]:
def predict_product(product_name):

    # Filter product data
    product_data = product_weekly[
        product_weekly["Product_Name"]
        == product_name
    ]

    # Check if product exists
    if len(product_data) == 0:
        print("Product not found!")
        return

    # Get latest row
    latest_row = product_data.iloc[-1]

    # Encode product
    encoded_product = (
        product_encoder.transform(
            [product_name]
        )[0]
    )

    # Encode category
    encoded_category = (
        category_encoder.transform(
            [latest_row["Category"]]
        )[0]
    )

    # Encode brand
    encoded_brand = (
        brand_encoder.transform(
            [latest_row["Brand"]]
        )[0]
    )

    # Create input dataframe
    input_data = pd.DataFrame({
        "Product_Encoded":
        [encoded_product],

        "Category_Encoded":
        [encoded_category],

        "Brand_Encoded":
        [encoded_brand],

        "Week":
        [latest_row["Week"]],

        "Month":
        [latest_row["Month"]],

        "Weekly_Revenue":
        [latest_row["Weekly_Revenue"]],

        "Weekly_Margin":
        [latest_row["Weekly_Margin"]],

        "Average_Stock":
        [latest_row["Average_Stock"]],

        "Lag_1":
        [latest_row["Lag_1"]],

        "Lag_2":
        [latest_row["Lag_2"]],

        "Lag_3":
        [latest_row["Lag_3"]],

        "Lag_4":
        [latest_row["Lag_4"]],

        "Rolling_4_Week_Avg":
        [latest_row[
            "Rolling_4_Week_Avg"
        ]],

        "Rolling_8_Week_Avg":
        [latest_row[
            "Rolling_8_Week_Avg"
        ]]
    })

    # Predict
    prediction = model.predict(
        input_data
    )[0]

    print(
        f"Predicted next week demand for "
        f"{product_name}: "
        f"{round(prediction)} units"
    )

In [133]:
predict_product("Tata Salt")

Predicted next week demand for Tata Salt: 17 units

In [132]:
print(
    sorted(
        product_weekly[
            "Product_Name"
        ].unique()
    )
)

['50-50 Biscuit', '7UP Bottle', 'Aashirvaad Atta', 'Amul Butter', 'Amul Cheese', 'Amul Curd', 'Amul Milk', 'Apple Pack', 'Banana Pack', 'Bingo Chips', 'Clinic Plus Shampoo', 'Comfort Fabric', 'Doritos Nacho', 'Dove Soap', 'Good Day Biscuit', 'Hide & Seek', 'Kurkure Masala', 'Lays Classic', 'Lays Magic Masala', 'Lux Soap', 'Marie Gold', 'Milo Drink', 'Monaco Biscuits', 'Mountain Dew', 'Nescafe Coffee', 'Nestle Greek Yogurt', 'Nestle Milk Powder', 'Nestle Yogurt', 'Onion Pack', 'Orange Pack', 'Parle-G Biscuits', 'Pepsi 750ml', 'Potato Pack', 'Sunfeast Biscuits', 'Sunfeast Pasta', 'Surf Excel', 'Tata Cleaning Powder', 'Tata Coffee', 'Tata Rice', 'Tata Salt', 'Tata Sampann Dal', 'Tata Tea', 'Tomato Pack', 'Vim Liquid', 'Yippee Noodles']

In [134]:
snacks_data = category_weekly[
    category_weekly["Category"]
    == "Snacks"
]

snacks_data = snacks_data.sort_values(
    by=["Year", "Week"]
)

print(snacks_data.head())

     Year  Week Category  Weekly_Units_Sold  Weekly_Revenue  Weekly_Margin  \
288  2024     4   Snacks                357    46641.579752    9659.240860
289  2024     5   Snacks                402    56877.825903   11439.942220
290  2024     6   Snacks                379    50769.902622   10617.230824
291  2024     7   Snacks                293    37622.197651    7927.516718
292  2024     8   Snacks                355    41347.540081    8270.263878

     Lag_1  Lag_2  Lag_3  Rolling_4_Week_Avg  Target  Category_Encoded
288  355.0  402.0  436.0              387.50   402.0                 6
289  357.0  355.0  402.0              379.00   379.0                 6
290  402.0  357.0  355.0              373.25   293.0                 6
291  379.0  402.0  357.0              357.75   355.0                 6
292  293.0  379.0  402.0              357.25   366.0                 6

In [135]:
sales_data = snacks_data[
    "Weekly_Units_Sold"
]

train_size = int(
    len(sales_data) * 0.8
)

train = sales_data[
    :train_size
]

test = sales_data[
    train_size:
]

print(len(train))
print(len(test))

38
10

In [136]:
from statsmodels.tsa.arima.model import (
    ARIMA
)

arima_model = ARIMA(
    train,
    order=(2,1,2)
)

arima_result = (
    arima_model.fit()
)

print("ARIMA trained!")

ARIMA trained!

c:\Users\user\DFIM project\.venv\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [137]:
predictions = (
    arima_result.forecast(
        steps=len(test)
    )
)

print(predictions)

326    344.747933
327    339.630935
328    357.074147
329    342.692470
330    357.834331
331    342.881452
332    357.881085
333    342.893246
334    357.883832
335    342.894111
Name: predicted_mean, dtype: float64

In [138]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(
    test,
    predictions
)

rmse = (
    mean_squared_error(
        test,
        predictions
    )
) ** 0.5

r2 = r2_score(
    test,
    predictions
)

print("ARIMA MAE:", mae)
print("ARIMA RMSE:", rmse)
print("ARIMA R2:", r2)

ARIMA MAE: 37.50510782984234
ARIMA RMSE: 49.75427959600456
ARIMA R2: -0.24712253048796717

In [145]:
!pip install tensorflow==2.15.0

ERROR: Could not find a version that satisfies the requirement tensorflow==2.15.0 (from versions: none)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for tensorflow==2.15.0

In [141]:
import numpy as np

from sklearn.preprocessing import (
    MinMaxScaler
)

from tensorflow.keras.models import (
    Sequential
)

from tensorflow.keras.layers import (
    LSTM,
    Dense
)

ModuleNotFoundError: No module named 'tensorflow'

In [172]:
import joblib

joblib.dump(
    model,
    "../models/product_xgboost_model.pkl"
)

print("Product model saved!")

Product model saved!

In [173]:
joblib.dump(
    category_model,
    "../models/category_xgboost_model.pkl"
)

print("Category model saved!")

Category model saved!

In [174]:
joblib.dump(
    product_encoder,
    "../models/product_encoder.pkl"
)

joblib.dump(
    category_encoder,
    "../models/category_encoder.pkl"
)

joblib.dump(
    brand_encoder,
    "../models/brand_encoder.pkl"
)

print("Encoders saved!")

Encoders saved!

In [175]:
loaded_model = joblib.load(
    "../models/category_xgboost_model.pkl"
)

print(
    "Model loaded successfully!"
)

Model loaded successfully!